version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8081:8081"
  db:
    image: postgres:12.3-alpine
    container_name: db
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGPORT: 5433
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  discovery:
    build: ./discovery
    container_name: discovery
    ports:
      - "8761:8761"
  api-gw:
    build: ./api
    container_name: api-gw
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    depends_on:
      - discovery
  user-service:
    build: ./user
    container_name: user-service
    ports:
      - "9000:9000"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
    depends_on:
      - db
      - discovery
  
  area-service:
    build: ./zone
    container_name: area-service
    ports:
      - "9008:9008"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
    depends_on:
      - db
      - discovery
  
  send-email:
    build: ./email
    container_name: send-email
    ports:
      - "9001:9001"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    depends_on:
      - db
      - discovery
  
#   payment-service:
#     build: ./payment
#     container_name: payment-service
#     ports:
#       - "9010:9010"
#     environment:
#       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
#       SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/postgres
#       SPRING_JPA_HIBERNATE_DDL-AUTO: create
#     depends_on:
#       - db
#       - discovery
#   blockchain-service:
#     build: ./blockchain (node 1)
#     container_name: blockchain-service
# #    ports:
# #      - "9011:9011"
#     environment:
#       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
#       SPRING_RABBITMQ_HOST: amqp://guest:guest@localhost:5672
#     depends_on:
#       - rabbitmq
#       - discovery
#     network_mode: host
#   blockchain-service2:
#     build: ./blockchain2
#     container_name: blockchain (node 2)
# #    ports:
# #      - "9012:9012"
#     environment:
#       EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
#       SPRING_RABBITMQ_HOST: amqp://guest:guest@localhost:5672
#     depends_on:
#       - rabbitmq
#       - discovery
#     network_mode: host
  car-insertion:
    build: ./car-insertion
    container_name: car-insertion
    ports:
      - "9002:9002"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
    depends_on:
      - db
      - discovery
  car-search:
    build: ./car-search
    container_name: car-search
    ports:
      - "9003:9003"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    depends_on:
      - db
      - discovery
      - car-insertion
  car-rating:
    build: ./car-rating
    container_name: car-rating
    ports:
      - "9004:9004"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
    depends_on:
      - db
      - discovery
      - car-insertion
  car-book:
    build: ./car-book
    container_name: car-book
    ports:
      - "9005:9005"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
    depends_on:
      - db
      - rabbitmq
      - discovery
      - car-search
     # network_mode: host
  chat:
    build: ./chat
    container_name: chat
    ports:
      - "9006:9006"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/postgres
      BROKER_RELAY_HOST: chat
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
    depends_on:
      - db
  notification-service:
    build: ./notification
    container_name: notification-service
    ports:
     - "9007:9007"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      
    depends_on:
      - rabbitmq
      - discovery
    # network_mode: host
