version: '3'
services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGPORT: 5433
  discovery:
    build: ./docker/discovery
    container_name: discovery
    ports:
      - "8761:8761"
  api-gw:
    build: ./docker/api
    container_name: api-gw
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
  user-service:
    build: ./docker/user
    container_name: user-service
    ports:
      - "9000:9000"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
    depends_on:
      - db
