server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: CARINSERTION-SERVICE
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
 #   defer-datasource-initialization: true
 # sql:
 #   init:
 #     mode: always
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost:5672