server:
  port: 9012
  error:
    include-message: always
    include-binding-errors:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: blockchain-node2-service
  rabbitmq:
    username: guest
    password: guest
    addresses: rabbitmq:5672

logging:
  level:
    root: ERROR
    org:
      springframework:
        main: ERROR