server:
  port: 9005

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: CARBOOK-SERVICE
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost:5672

rabbitmq:
  message-queue: car_subscription_queue
  message-exchange: car_subscription_exchange
  mq-routing-key: 123456789

app:
  subscription-service-url: http://localhost:9005